### PR TITLE
Entry generators 10

### PR DESCRIPTION
**Pull request by Cjk01**

### CODE REVIEW

**Review by Cjk01 — COMMENTED** [review]
@JonahOsborne 
from what I can tell looking at the files changed, it seems like that although your changes appear in the documentation, your changes do not actually appear within the pull request. I suspect that you may have not added those files within your commit before making the PR
I should see changes in src/client/{...}

for the generator

**Comment by JonahOsborne** [comment]
Honestly not sure why the other commits didn't include the script file, but should be good now.

**Comment by Cjk01** [comment]
@JonahOsborne 
I reviewed it , looks good to me. Some small changes though.
- Abstract the styling into styles.css for the generated elements
You add classes and ids, but you also manually set the styles within js. I would place these styles within the css file instead, under .classname and #id for your generated elements. 

For example
```
 // Creation of entire entry
    let entry = document.createElement("div");
    entry.classList.add("deck-entry");

    entry.style.width = 700;
    entry.style.height = 150;
    entry.style.margin = 10;
    entry.style.display = "grid";
    entry.style.gridTemplateColumns = "3fr 1fr";
    entry.style.border = "solid";
```
You can add .deck-entry to styles.css and add your styles in there. In general, any time you use some element.style in a js file, it should instead be in the .css file. Not only will it make the code simpler, but if we have nothing in our .css file and only use styles within our .js files, I think we would have points taken off. 

Otherwise gj and I like the changes.

**Comment by Cjk01** [comment]
Nice, merged

**Pull request merged**
